### PR TITLE
[Work in progress] Get examples to work as they come

### PR DESCRIPTION
**Pull request by peppelinux**
The road to the first test:
    
    - Added private keys for running tests
    - Added oidc_op conf_fed.yaml (still have to put there the add_ons extensions)
    - Patched fedservice.__init__#142 to elude the absence of addons configuration
    - Patched flask_rp_expl.application.init_oidc_rp_handler to handle the updated configuration (followin JWT-Connect-Python-OidcRP)
    - Other minor changes in flask_rp_expl (added also a conf_fed.yml)

### CODE REVIEW

**Comment by rohe** [comment]
I'ver worked a lot on mutual TLS lately. Turns out you can do some nifty things allowing servers to use self-signed certificates IF entities publish the certificate in the entity statement.
Unfortunately Flask for sure possibly also Python SSLContext has no support for self-signed client certificates which means there is no way to do MTLS unless you're using NGIX/Apache/.. as a frontend.

**Comment by rohe** [comment]
Sitting on a train with spotty Internet access working on the federation example.

**Comment by rohe** [comment]
Give me a couple of hours and you will have something that works a bit better than the present.
Moving from python configuration files to just YAML for the examples.

**Comment by peppelinux** [comment]
````
hostname = 'www.python.org'
# PROTOCOL_TLS_CLIENT requires valid cert chain and hostname
context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.load_verify_locations('path/to/cabundle.pem')
````

https://docs.python.org/3/library/ssl.html see `ssl.create_default_context`
The most important thing is that the MTLS are always mediate by a CA, even if it's private/homebrew

**Comment by peppelinux** [comment]
> Give me a couple of hours and you will have something that works a bit better than the present.
> Moving from python configuration files to just YAML for the examples.

I just threw the boulder into the lake, I know your response times well, you work better than a fire station. Don't stress, I await your push, I'm definitely in the Fed Connect and I'll go deep until I have a clear view of the whole and the application prototype

**Comment by peppelinux** [comment]
You did It here
https://github.com/rohe/fedservice/commit/2804b1114d0a1040916a499c5d9bdb3d9c398195

Going to test It, thx

**Pull request closed without merging**
